import { FormEvent, ReactNode, useCallback, useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Bell, ChevronRight, CircleDollarSign, LayoutDashboard, LogOut, PiggyBank, Plus, ReceiptText, Tags, Target, Trash2, X } from 'lucide-react';
import FinanceScene from './FinanceScene';
import { api } from './api';

type Tx={id:number;amount:number;date:string;category:string;description?:string;type:'INCOME'|'EXPENSE'};
type Goal={id:number;goalName:string;targetAmount:number;targetDate:string;startDate:string;currentProgress:number;progressPercentage:number;remainingAmount:number};
type Category={id:number;name:string;type:'INCOME'|'EXPENSE';isCustom:boolean};
type View='overview'|'transactions'|'categories'|'goals';
type ModalType='transaction'|'goal'|'category'|null;
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const today=new Date().toISOString().slice(0,10);

export default function Workspace(){
 const [auth,setAuth]=useState<'loading'|'guest'|'user'>('loading');
 const [view,setView]=useState<View>('overview');
 const [transactions,setTransactions]=useState<Tx[]>([]);
 const [goals,setGoals]=useState<Goal[]>([]);
 const [categories,setCategories]=useState<Category[]>([]);
 const [modal,setModal]=useState<ModalType>(null);
 const [toast,setToast]=useState('');
 const load=useCallback(async()=>{try{const[t,g,c]=await Promise.all([api<{transactions:Tx[]}>('/transactions'),api<{goals:Goal[]}>('/goals'),api<{categories:Category[]}>('/categories')]);setTransactions(t.transactions);setGoals(g.goals);setCategories(c.categories);setAuth('user')}catch{setAuth('guest')}},[]);
 useEffect(()=>{load()},[load]);
 const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),2400)};
 const remove=async(path:string,message:string)=>{await api(path,{method:'DELETE'});notify(message);load()};
 if(auth==='loading')return <div className="splash"><CircleDollarSign/><span>Folio</span></div>;
 if(auth==='guest')return <Auth onSuccess={load}/>;
 const income=transactions.filter(x=>x.type==='INCOME').reduce((s,x)=>s+Number(x.amount),0);
 const expense=transactions.filter(x=>x.type==='EXPENSE').reduce((s,x)=>s+Number(x.amount),0);
 return <div className="shell">
  <aside><a className="brand"><span><CircleDollarSign/></span>Folio</a><nav>
   <Nav active={view==='overview'} icon={<LayoutDashboard/>} text="Overview" go={()=>setView('overview')}/>
   <Nav active={view==='transactions'} icon={<ReceiptText/>} text="Transactions" go={()=>setView('transactions')}/>
   <Nav active={view==='categories'} icon={<Tags/>} text="Categories" go={()=>setView('categories')}/>
   <Nav active={view==='goals'} icon={<Target/>} text="Savings goals" go={()=>setView('goals')}/>
  </nav><div className="pro-card"><PiggyBank/><b>Build your safety net</b><p>A little progress every day creates lasting freedom.</p><button onClick={()=>setModal('goal')}>Create a goal <ChevronRight size={15}/></button></div><button className="logout" onClick={async()=>{await api('/auth/logout',{method:'POST'});setAuth('guest')}}><LogOut/>Sign out</button></aside>
  <main><Header view={view} add={()=>setModal(view==='categories'?'category':view==='goals'?'goal':'transaction')}/>
   {view==='overview'&&<Overview income={income} expense={expense} transactions={transactions} goals={goals} add={setModal} remove={remove}/>} 
   {view==='transactions'&&<TransactionsPage items={transactions} add={()=>setModal('transaction')} remove={id=>remove(`/transactions/${id}`,'Transaction deleted')}/>} 
   {view==='categories'&&<CategoriesPage items={categories} add={()=>setModal('category')} remove={name=>remove(`/categories/${encodeURIComponent(name)}`,'Category deleted')}/>} 
   {view==='goals'&&<GoalsPage items={goals} add={()=>setModal('goal')} remove={id=>remove(`/goals/${id}`,'Goal deleted')}/>} 
  </main>
  {modal&&<Modal title={modal==='transaction'?'Add movement':modal==='goal'?'Create a goal':'New category'} close={()=>setModal(null)}>{modal==='transaction'?<TransactionForm categories={categories} done={()=>{setModal(null);notify('Transaction added');load()}}/>:modal==='goal'?<GoalForm done={()=>{setModal(null);notify('Goal created');load()}}/>:<CategoryForm done={()=>{setModal(null);notify('Category created');load()}}/>}</Modal>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}

function Nav({active,icon,text,go}:{active:boolean;icon:ReactNode;text:string;go:()=>void}){return <a className={active?'active':''} onClick={go}>{icon}{text}</a>}
function Header({view,add}:{view:View;add:()=>void}){const titles={overview:'Good to see you, investor.',transactions:'Every movement, accounted for.',categories:'Organize money your way.',goals:'Make ambition measurable.'};return <header><div><p className="eyebrow">YOUR MONEY, CLEARLY</p><h1>{titles[view]}</h1></div><div className="actions"><span className="status live">Live data</span><button className="icon" aria-label="Notifications"><Bell/></button><button className="primary" onClick={add}><Plus/>Add {view==='goals'?'goal':view==='categories'?'category':'transaction'}</button></div></header>}
function Overview({income,expense,transactions,goals,add,remove}:{income:number;expense:number;transactions:Tx[];goals:Goal[];add:(m:ModalType)=>void;remove:(p:string,m:string)=>void}){return <><section className="hero"><div className="hero-copy"><span className="pill">YOUR FINANCIAL ORBIT</span><h2>Money in motion,<br/><i>future in focus.</i></h2><p>Every choice shapes your financial landscape. Keep the momentum going.</p><div className="hero-metric"><span>Available balance</span><strong>{money(income-expense)}</strong><small><ArrowUpRight/> Your live net position</small></div></div><div className="scene"><FinanceScene/></div></section><section className="metrics"><Metric title="Income" value={money(income)} text={`${transactions.filter(x=>x.type==='INCOME').length} recorded payments`} icon={<ArrowUpRight/>}/><Metric title="Expenses" value={money(expense)} text={`${income?Math.round(expense/income*100):0}% of total income`} icon={<ArrowDownRight/>}/><Metric title="Savings rate" value={`${income?Math.max(0,Math.round((income-expense)/income*100)):0}%`} text="Keep building financial freedom" icon={<PiggyBank/>}/></section><section className="lower"><article className="panel"><PanelTitle eyebrow="CASH FLOW" title="Recent movement" add={()=>add('transaction')}/><TransactionList items={transactions.slice(0,5)} remove={id=>remove(`/transactions/${id}`,'Transaction deleted')}/></article><article className="panel goals"><PanelTitle eyebrow="GOALS" title="Your next milestone" add={()=>add('goal')}/>{goals.length?<GoalRing goal={goals[0]}/>:<Empty text="Create a goal and watch your progress grow."/>}</article></section></>}
function TransactionsPage({items,add,remove}:{items:Tx[];add:()=>void;remove:(id:number)=>void}){return <section className="page-view"><PageIntro eyebrow="CASH FLOW LEDGER" title="Transactions" text="A complete timeline of your financial activity."/><article className="panel full-panel"><PanelTitle eyebrow={`${items.length} ENTRIES`} title="All movements" add={add}/><TransactionList items={items} remove={remove}/></article></section>}
function CategoriesPage({items,add,remove}:{items:Category[];add:()=>void;remove:(name:string)=>void}){return <section className="page-view"><PageIntro eyebrow="YOUR TAXONOMY" title="Categories" text="Give every rupee a purpose with clear income and expense groups."/><div className="category-grid">{items.map(c=><article className="category-card" key={c.id}><span className={`category-symbol ${c.type.toLowerCase()}`}>{c.type==='INCOME'?<ArrowUpRight/>:<ArrowDownRight/>}</span><div><b>{c.name}</b><small>{c.type} · {c.isCustom?'CUSTOM':'FOLIO DEFAULT'}</small></div>{c.isCustom&&<button aria-label={`Delete ${c.name}`} onClick={()=>remove(c.name)}><Trash2/></button>}</article>)}<button className="add-card" onClick={add}><Plus/><span>Create custom category</span></button></div></section>}
function GoalsPage({items,add,remove}:{items:Goal[];add:()=>void;remove:(id:number)=>void}){return <section className="page-view"><PageIntro eyebrow="FUTURE FUND" title="Savings goals" text="Turn distant plans into visible, measurable progress."/><div className="goals-grid">{items.map(g=><article className="panel goal-card" key={g.id}><button className="delete goal-delete" aria-label={`Delete ${g.goalName}`} onClick={()=>remove(g.id)}><Trash2/></button><GoalRing goal={g}/><small>Target date · {new Date(g.targetDate).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</small></article>)}<button className="add-card goal-add" onClick={add}><Plus/><span>Create your next milestone</span></button></div></section>}
function PageIntro({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="page-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>}
function PanelTitle({eyebrow,title,add}:{eyebrow:string;title:string;add:()=>void}){return <div className="panel-head"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div><button onClick={add}><Plus/> Add</button></div>}
function Metric({title,value,text,icon}:{title:string;value:string;text:string;icon:ReactNode}){return <article><div><span>{title}</span>{icon}</div><strong>{value}</strong><p>{text}</p></article>}
function TransactionList({items,remove}:{items:Tx[];remove:(id:number)=>void}){return <div className="tx-list">{items.length===0?<Empty text="Your first transaction will appear here."/>:items.map(tx=><div className="tx" key={tx.id}><span className={`tx-icon ${tx.type.toLowerCase()}`}>{tx.type==='INCOME'?<ArrowUpRight/>:<ArrowDownRight/>}</span><div><b>{tx.description||tx.category}</b><small>{tx.category} · {new Date(tx.date).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</small></div><strong className={tx.type.toLowerCase()}>{tx.type==='INCOME'?'+':'-'}{money(Number(tx.amount))}</strong><button className="delete" aria-label="Delete transaction" onClick={()=>remove(tx.id)}><X/></button></div>)}</div>}

function Auth({onSuccess}:{onSuccess:()=>void}){const[mode,setMode]=useState<'login'|'register'>('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=Object.fromEntries(new FormData(e.currentTarget));try{if(mode==='register')await api('/auth/register',{method:'POST',body:JSON.stringify({...d,phoneNumber:String(d.phoneNumber).replaceAll(' ','')})});await api('/auth/login',{method:'POST',body:JSON.stringify({username:d.username,password:d.password})});onSuccess()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}return <div className="auth"><div className="auth-scene"><FinanceScene/></div><div className="auth-copy"><a className="brand"><span><CircleDollarSign/></span>Folio</a><span className="pill">PERSONAL FINANCE, REIMAGINED</span><h2>Turn everyday choices into <i>lasting freedom.</i></h2><p>A calm, visual home for your income, spending, and ambitions.</p></div><form className="auth-card" onSubmit={submit}><span className="eyebrow">WELCOME TO FOLIO</span><h1>{mode==='login'?'Enter your financial orbit':'Begin your journey'}</h1><p>{mode==='login'?'Sign in to see your money in motion.':'Create your private finance workspace.'}</p>{error&&<div className="form-error">{error}</div>}<label>Email<input name="username" type="email" required/></label>{mode==='register'&&<><label>Full name<input name="fullName" required/></label><label>Phone number<input name="phoneNumber" placeholder="+91 9876543210" required/></label></>}<label>Password<input name="password" type="password" minLength={8} required/></label><button className="submit" disabled={busy}>{busy?'Please wait...':mode==='login'?'Sign in':'Create account'} <ArrowUpRight/></button><button type="button" className="switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New here? Create an account':'Already a member? Sign in'}</button></form></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-title"><div><span className="eyebrow">FOLIO WORKSPACE</span><h3>{title}</h3></div><button onClick={close}><X/></button></div>{children}</div></div>}
function DataForm({endpoint,done,transform=(x)=>x,children}:{endpoint:string;done:()=>void;transform?:(x:Record<string,FormDataEntryValue>)=>object;children:ReactNode}){const[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();try{await api(endpoint,{method:'POST',body:JSON.stringify(transform(Object.fromEntries(new FormData(e.currentTarget))))});done()}catch(x){setError((x as Error).message)}}return <form className="data-form" onSubmit={submit}>{error&&<div className="form-error">{error}</div>}{children}</form>}
function TransactionForm({categories,done}:{categories:Category[];done:()=>void}){return <DataForm endpoint="/transactions" done={done} transform={d=>({...d,amount:Number(d.amount)})}><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Date<input name="date" type="date" max={today} defaultValue={today} required/></label><label>Category<select name="category" required><option value="">Choose category</option>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select></label><label>Description<input name="description"/></label><button className="submit">Save transaction <ArrowUpRight/></button></DataForm>}
function GoalForm({done}:{done:()=>void}){return <DataForm endpoint="/goals" done={done} transform={d=>({...d,targetAmount:Number(d.targetAmount)})}><label>Goal name<input name="goalName" required/></label><label>Target amount<input name="targetAmount" type="number" min="0.01" step="0.01" required/></label><label>Target date<input name="targetDate" type="date" min={new Date(Date.now()+86400000).toISOString().slice(0,10)} required/></label><label>Start date<input name="startDate" type="date" max={today} defaultValue={today}/></label><button className="submit">Create goal <Target/></button></DataForm>}
function CategoryForm({done}:{done:()=>void}){return <DataForm endpoint="/categories" done={done}><label>Name<input name="name" required/></label><label>Type<select name="type"><option value="INCOME">Income</option><option value="EXPENSE">Expense</option></select></label><button className="submit">Create category <Tags/></button></DataForm>}
function GoalRing({goal}:{goal:Goal}){return <div className="goal-body"><div className="ring" style={{'--progress':`${goal.progressPercentage*3.6}deg`} as React.CSSProperties}><span><strong>{Math.round(goal.progressPercentage)}%</strong><small>complete</small></span></div><h4>{goal.goalName}</h4><p>{money(goal.currentProgress)} saved of {money(goal.targetAmount)}</p><div className="goal-foot"><span>Remaining</span><b>{money(goal.remainingAmount)}</b></div></div>}
function Empty({text}:{text:string}){return <div className="empty"><span><Plus/></span><p>{text}</p></div>}
